# Generated by Django 3.2.3 on 2021-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
