# Generated by Django 3.2.3 on 2021-06-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0002_user_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domicilio',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='urgente',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
