# Generated by Django 3.2.3 on 2021-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0003_auto_20210612_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='domicilio',
            field=models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='urgente',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
