# Generated by Django 3.2.3 on 2021-06-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0004_auto_20210612_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.PositiveSmallIntegerField()),
                ('interpretacion', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('domicilio', models.CharField(choices=[('yes', 'Sí'), ('no', 'No')], max_length=3)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=45)),
                ('municipio', models.CharField(max_length=30)),
                ('urgente', models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], max_length=3, null=True)),
                ('nombre_2', models.CharField(max_length=30)),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(max_length=11)),
            ],
        ),
    ]
