# Generated by Django 3.2.3 on 2021-06-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0006_alter_user_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='domicilio',
            field=models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], max_length=3, null=True),
        ),
    ]
