# Generated by Django 3.2.3 on 2021-06-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0007_alter_form_domicilio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
