# Generated by Django 3.2.3 on 2021-06-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('edad', models.CharField(max_length=30)),
                ('interpretacion', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=3, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('urgente', models.CharField(blank=True, choices=[('yes', 'Sí'), ('no', 'No')], max_length=3, null=True)),
                ('nombre_2', models.CharField(max_length=30)),
                ('apellido_2', models.CharField(blank=True, max_length=30, null=True)),
                ('celular', models.CharField(max_length=11)),
            ],
        ),
    ]
