# Generated by Django 3.2.3 on 2021-06-30 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0010_form_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='edad',
            field=models.CharField(max_length=30),
        ),
    ]
