# Generated by Django 3.2.3 on 2021-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0011_alter_form_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='address',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
