# Generated by Django 3.2.3 on 2021-06-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0013_auto_20210630_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuantovaser',
            name='address',
            field=models.CharField(default=float("nan"), max_length=200),
        ),
    ]
