# Generated by Django 3.2.3 on 2021-07-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0014_alter_cuantovaser_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuantovaser',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='apellido_2',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='interpretacion',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='nombre_2',
        ),
        migrations.RemoveField(
            model_name='cuantovaser',
            name='urgente',
        ),
        migrations.AlterField(
            model_name='cuantovaser',
            name='address',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
