# Generated by Django 3.2.3 on 2021-07-04 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cta', '0015_auto_20210703_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='address',
        ),
    ]
